# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DlHpXfujBW98XVDL0R0ViE3YX_2csPX
"""

#DATOS  Aprendizaje Maquina Prof. López Aramburo María Fernanda Ciclo 2026B - Sección D05

#Ingeneria en Computacion
#Jauregui Esparza Diego Yael 219626423
#García Pérez Jesús Emmanuel 221410985
#Puebla Nieto Jorge Iván 224785429
#Noriega Vazquez Diego Eleazar 217123459

#Ingresamos librerias

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Ingresamos los datos

# La primera columna corresponde a las horas de estudio
# La segunda columna corresponde a las tareas realizadas

X = np.array([
    [5, 8],
    [20, 2],
    [5, 9],
    [15, 11],
    [10, 10],
    [8, 7],
    [12, 10],
    [18, 3],
    [6, 8],
    [14, 12],
    [9, 9],
    [16, 5],
    [7, 6],
    [11, 11],
    [13, 8],
    [4, 10],
    [17, 4],
    [19, 1],
    [3, 12],
    [10, 7],
    [6, 9],
    [14, 6],
    [8, 8],
    [12, 10],
    [15, 5],
    [7, 11],
    [9, 7],
    [11, 9],
    [13, 12],
    [16, 4]
])

# Ingresamos las calificaciones reales

y = np.array((
    10, 30, 20, 25, 15,
    18, 22, 28, 12, 24,
    17, 26, 14, 23, 21,
    8, 27, 32, 6, 19,
    13, 25, 16, 20, 29,
    15, 18, 12, 24, 31
))

# Los datos se dividen en proporcion 70 - 30

X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.30,

    random_state=42

)

print("Datos de entrenamiento:")
print(X_train)

print("\nCalificaciones de entrenamiento:")
print(y_train)

print("\nDatos de prueba:")
print(X_test)

print("\nCalificaciones de prueba:")
print(y_test)

# Toca crear el modelo de regresion lineal multiple

regresion = LinearRegression()

# Se entrena el modelo

modelo = regresion.fit(X_train, y_train)

# Se obtiene la interseccion y los pesos del modelo

interseccion = modelo.intercept_

peso_estudio = modelo.coef_[0]

peso_tareas = modelo.coef_[1]


# Mostrar los valores obtenidos

print("\nResultados del modelo:")

print("Theta 0 (Interseccion):", interseccion)

print("Theta 1 (Peso de Estudio):", peso_estudio)

print("Theta 2 (Peso de Tareas):", peso_tareas)

# Mostrar la ecuacion del modelo

print("\nEcuacion del modelo:")

print(
    "Calificacion =",
    interseccion,
    "+",
    peso_estudio,
    "* Horas de estudio",
    "+",
    peso_tareas,
    "* Tareas realizadas"
)

# Iniciamos las predicciones con los valores obtenidos

y_pred_test = modelo.predict(X_test)

# Mostrar las calificaciones reales y las calificaciones predichas

print("\nCalificaciones reales de prueba:")
print(y_test)

print("\nCalificaciones predichas:")
print(y_pred_test)

# Se crea un DataFrame que incluye:
# Horas de estudio
# Tareas realizadas
# Calificacion real
# Calificacion predicha

tabla_resultados = pd.DataFrame({
    "Horas estudio": X_test[:, 0],
    "Tareas realizadas": X_test[:, 1],
    "Calificacion real": y_test,
    "Calificacion predicha": y_pred_test
})

# Calcular el error entre la calificacion real
# y la calificacion predicha

tabla_resultados["Error"] = (
    tabla_resultados["Calificacion real"]
    - tabla_resultados["Calificacion predicha"]
)

# Ordenar la tabla por horas de estudio

tabla_resultados = tabla_resultados.sort_values("Horas estudio")

# Mostrar la tabla de resultados

print("\nTabla de resultados:")
print(tabla_resultados)

# Cálculo e impresión de métricas de evaluación
mse = mean_squared_error(y_test, y_pred_test)
rmse = np.sqrt(mse) # O bien: root_mean_squared_error(y_test, y_pred_test)
r2 = r2_score(y_test, y_pred_test)

print("\nMétricas de evaluación:")
print("Error Cuadrático Medio (MSE):", mse)
print("Raíz del Error Cuadrático Medio (RMSE):", rmse)
print("Coeficiente de determinación (R2):", r2)


# Se grafican los datos
# Los de entrenamiento se muestran en azul
# Los de prueba se muestran en rosa

plt.scatter(
    X_train[:, 0],
    y_train,
    color="blue",
    label="Entrenamiento"
)

plt.scatter(
    X_test[:, 0],
    y_test,
    color="pink",
    label="Prueba"
)

plt.xlabel("Horas de estudio")
plt.ylabel("Calificación real")
plt.title("Datos de entrenamiento y prueba")
plt.legend()
plt.grid(True)

plt.show()

# Importar herramienta para realizar graficas 3D

from mpl_toolkits.mplot3d import Axes3D

# Crear la figura

fig = plt.figure(figsize=(10, 7))

# Crear un eje tridimensional

ax = fig.add_subplot(111, projection="3d")


# Graficar los datos reales

ax.scatter(
    X_train[:, 0],
    X_train[:, 1],
    y_train,
    color="blue",
    label="Entrenamiento"
)

ax.scatter(
    X_test[:, 0],
    X_test[:, 1],
    y_test,
    color="pink",
    label="Prueba"
)


# Crear una malla de valores para construir
# el plano de regresion

horas = np.linspace(
    X[:, 0].min(),
    X[:, 0].max(),
    20
)

tareas = np.linspace(
    X[:, 1].min(),
    X[:, 1].max(),
    20
)

horas_malla, tareas_malla = np.meshgrid(
    horas,
    tareas
)


# Calcular las predicciones del modelo
# para cada punto de la malla

calificaciones_malla = (
    interseccion
    + peso_estudio * horas_malla
    + peso_tareas * tareas_malla
)


# Dibujar el plano de regresion

ax.plot_surface(
    horas_malla,
    tareas_malla,
    calificaciones_malla,
    alpha=0.4
)


# Colocar nombres a los ejes

ax.set_xlabel("Horas de estudio")
ax.set_ylabel("Tareas realizadas")
ax.set_zlabel("Calificación")


# Titulo de la grafica

ax.set_title("Regresión lineal múltiple")


# Mostrar leyenda

ax.legend()

# Mostrar grafica

plt.show()